HelixLaserWorks/Areas/Admin/Controllers/OrderController.cs
using HelixLaserWorks.Core.Contracts;
using HelixLaserWorks.Core.Models.Order;
using HelixLaserWorks.Infrastructure.Data.Models.Enumerators;
using Microsoft.AspNetCore.Mvc;

namespace HelixLaserWorks.Areas.Admin.Controllers
{
    public class OrderController : BaseAdminController
    {
        private readonly IOrderService _orderService;
        private readonly IPartService _partService;

        public OrderController(IOrderService orderService, IPartService partService)
        {
            _orderService = orderService;
            _partService = partService;
        }


        [HttpGet]//ADMIN ONLY
        public async Task<IActionResult> CustomersOrders([FromQuery] OrderPaginatedViewModel model)
        {
            var orders = await _orderService.GetAllAsync(
                null,
                model.SearchTerm,
                model.Status,
                model.CurrentPage,
                OrderPaginatedViewModel.OrdersPerPage);

            model.TotalOrdersCount = orders.TotalOrdersCount;
            model.Orders = orders.Orders;

            return View(model);
        }

        [HttpPost]//ADMIN ONLY
        public async Task<IActionResult> MarkAsReviewed(int orderId)
        {
            if (!await _orderService.OrderExistAsync(orderId))
            {
                return BadRequest();
            }

            var orderStatus = await _orderService.GetOrderStatusAsync(orderId);

            if (orderStatus != OrderStatus.Pending)
            {
                return BadRequest();
            }

            await _orderService.MarkAsReviewdAsync(orderId);

            return RedirectToAction(nameof(CustomersOrders));
        }

        [HttpGet]//ADMIN ONLY
        public async Task<IActionResult> Decline(int orderId)
        {
            if (!await _orderService.OrderExistAsync(orderId))
            {
                return BadRequest();
            }

            var orderStatus = await _orderService.GetOrderStatusAsync(orderId);

            if (orderStatus == OrderStatus.DeclinedByAdmin ||
                orderStatus == OrderStatus.ReadyWithOffer)
            {
                return BadRequest();
            }

            var model = await _orderService.GetOrderForDeclineAsync(orderId);

            return View(model);
        }

        [HttpPost]//ADMIN ONLY
        public async Task<IActionResult> Decline(int orderId, OrderDeclineViewModel model)
        {
            if (!await _orderService.OrderExistAsync(orderId))
            {
                return BadRequest();
            }

            var orderStatus = await _orderService.GetOrderStatusAsync(orderId);

            if (orderStatus == OrderStatus.DeclinedByAdmin ||
                orderStatus == OrderStatus.ReadyWithOffer)
            {
                return BadRequest();
            }

            if (!ModelState.IsValid)
            {
                model = await _orderService.GetOrderForDeclineAsync(orderId);
                return View(model);
            }

            await _orderService.DeclineOrder(orderId, model);

            return RedirectToAction(nameof(CustomersOrders));
        }

        [HttpPost]//ADMIN ONLY
        public async Task<IActionResult> DeleteOrder(int orderId)
        {
            if (!await _orderService.OrderExistAsync(orderId))
            {
                return BadRequest();
            }

            await _orderService.DeleteOrderAsync(orderId);

            return RedirectToAction(nameof(CustomersOrders));
        }
    }
}

HelixLaserWorks/Controllers/OfferController.cs
using HelixLaserWorks.Core.Contracts;
using HelixLaserWorks.Core.Models.Offer;
using HelixLaserWorks.Hubs;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace HelixLaserWorks.Controllers
{
    public class OfferController : BaseController
    {
        private readonly IOfferService _offerService;
        private readonly IOrderService _orderService;
        private readonly IHubContext<NotificationHub> _hubContext;

        public OfferController(IOfferService offerService,
            IOrderService orderService,
            IHubContext<NotificationHub> hubContext)
        {
            _offerService = offerService;
            _orderService = orderService;
            _hubContext = hubContext;
        }

        [HttpGet]
        public async Task<IActionResult> Details(int offerId)
        {
            var model = await _offerService.GetOfferDetailsAsync(offerId);

            if (model == null)
            {
                return BadRequest();
            }

            if (model.Order.CustomerEmail != GetUserEmail())
            {
                return Unauthorized();
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> MyOffers()
        {
            var userId = GetUserId();

            var model = await _offerService.GetUserOffersAsync(userId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Accept(int offerId)
        {
            if (!await _offerService.OfferExistAsync(offerId) || await _offerService.OfferIsAcceptedAsync(offerId))
            {
                return BadRequest();
            }

            var userId = GetUserId();

            if (!await _offerService.UserIsOrderCreatorAsync(offerId, userId))
            {
                return Unauthorized();
            }

            await _offerService.AcceptOfferAsync(offerId);

            await _hubContext.Clients.All.SendAsync("ReceiveNotification", $"Customer {User.Identity?.Name} has accepted our offer, contact is required!");

            return RedirectToAction(nameof(OfferAccepted));
        }

        [HttpGet]
        public IActionResult OfferAccepted()
        {
            return View();
        }

    }
}

HelixLaserWorks/Controllers/OrderController.cs
using HelixLaserWorks.Core.Contracts;
using HelixLaserWorks.Core.Models.Order;
using HelixLaserWorks.Hubs;
using HelixLaserWorks.Infrastructure.Data.Constants;
using HelixLaserWorks.Infrastructure.Data.Models.Enumerators;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.SignalR;

namespace HelixLaserWorks.Controllers
{
    public class OrderController : BaseController
    {
        private readonly IOrderService _orderService;
        private readonly IPartService _partService;
        private readonly IHubContext<NotificationHub> _hubContext;

        public OrderController(IOrderService orderService, IPartService partService, IHubContext<NotificationHub> hubContext)
        {
            _orderService = orderService;
            _partService = partService;
            _hubContext = hubContext;
        }

        [HttpGet]
        public async Task<IActionResult> MyOrders([FromQuery] OrderPaginatedViewModel model)
        {
            string? userId = GetUserId();

            var orders = await _orderService.GetAllAsync(
                userId,
                model.SearchTerm,
                model.Status,
                model.CurrentPage,
                OrderPaginatedViewModel.OrdersPerPage);

            model.TotalOrdersCount = orders.TotalOrdersCount;
            model.Orders = orders.Orders;

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new OrderFormModel();
            string userId = GetUserId();

            model.UserParts = await _partService.GetUserPartsForDropdownAsync(userId);

            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(OrderFormModel model)
        {
            string userId = GetUserId();

            if (!model.SelectedParts.Any())
            {
                ModelState.AddModelError(nameof(model.SelectedParts), "You need to select atleast one part create an order!");
            }

            foreach (var partId in model.SelectedParts)
            {
                if (!await _partService.UserIsCreatorAsync(partId, userId))
                {
                    ModelState.AddModelError(nameof(model.SelectedParts), "Cannot add parts created by another user!");
                }

                if (!await _partService.PartExistsAsync(partId))
                {
                    ModelState.AddModelError(nameof(model.SelectedParts), "Part does not exist!");
                }
            }

            if (!ModelState.IsValid)
            {
                model.UserParts = await _partService.GetUserPartsForDropdownAsync(userId);
                return View(model);
            }

            await _orderService.CreateOrderAsync(userId, model);

            await _hubContext.Clients.All.SendAsync("ReceiveNotification", $"Customer {User.Identity?.Name} created new order : {model.Title}");

            return RedirectToAction(nameof(MyOrders));
        }

        [HttpPost]
        public async Task<IActionResult> Cancel(int orderId)
        {
            string userId = GetUserId();

            if (!await _orderService.OrderExistAsync(orderId))
            {
                return BadRequest();
            }

            var orderStatus = await _orderService.GetOrderStatusAsync(orderId);

            if (orderStatus != OrderStatus.DeclinedByAdmin &&
                orderStatus != OrderStatus.Pending)
            {
                return BadRequest();
            }

            if (!await _orderService.UserIsCreatorAsync(userId, orderId))
            {
                return Unauthorized();
            }

            await _orderService.CancelOrderAsync(orderId);

            return RedirectToAction(nameof(MyOrders));
        }

    }
}

HelixLaserWorks/Controllers/PartController.cs
using HelixLaserWorks.Core.Contracts;
using HelixLaserWorks.Core.Models.Part;
using Microsoft.AspNetCore.Mvc;

namespace HelixLaserWorks.Controllers
{

    public class PartController : BaseController
    {
        private readonly IPartService _partService;
        private readonly IMaterialService _materialService;
        private readonly IFileManageService _fileManageService;

        public PartController(IPartService partService,
            IMaterialService materialService,
            IFileManageService fileManageService)
        {
            _materialService = materialService;
            _partService = partService;
            _fileManageService = fileManageService;
        }

        [HttpGet]
        public async Task<IActionResult> MyParts([FromQuery] UserPartsQueryModel model)
        {
            string userId = GetUserId();

            var userParts = await _partService.GetUserPartsAsync(userId,
                model.Material,
                model.SearchTerm,
                model.Sorting,
                model.CurrentPage,
                UserPartsQueryModel.PartsPerPage
                );

            model.TotalPartsCount = userParts.TotalPartsCount;
            model.Parts = userParts.Parts;

            model.Materials = await _materialService.GetAllForDropdownAsync();

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var model = new PartFormModel();

            model.Materials = await _materialService.GetAllForDropdownAsync();
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> Create(PartFormModel model)
        {
            if (model.SchemeFile == null || model.SchemeFile.Length <= 0)
            {
                ModelState.AddModelError((nameof(model.SchemeFile)), "Part scheme file is required!");
            }

            if (!await _materialService.MaterialExistsAsync(model.MaterialId))
            {
                ModelState.AddModelError(nameof(model.MaterialId), "Invalid material!");
            }

            if (!await _materialService.MaterialThicknessExistsAsync(model.MaterialId, model.PartThickness))
            {
                ModelState.AddModelError(nameof(model.PartThickness), "Invalid thickness for given material!");
            }

            if (!ModelState.IsValid)
            {
                model.Materials = await _materialService.GetAllForDropdownAsync();

                return View(model);
            }
            string userId = GetUserId();
            string userEmail = GetUserEmail();

            if (model.SchemeFile != null)
            {
                await _partService.CreateAsync(model, userId, userEmail);
            }

            return RedirectToAction(nameof(MyParts));
        }

        [HttpGet]
        public async Task<IActionResult> Edit(int partId)
        {
            string userId = GetUserId();
            var partForEditModel = await _partService.GetPartForEditAsync(partId);

            if (partForEditModel == null || await _partService.IsOrdered(partId))
            {
                return BadRequest();
            }

            if (!await _partService.UserIsCreatorAsync(partId, userId))
            {
                return Unauthorized();
            }

            partForEditModel.Materials = await _materialService.GetAllForDropdownAsync();

            return View(partForEditModel);
        }

        [HttpPost]
        public async Task<IActionResult> Edit(int partId, PartFormModel model)
        {
            string userId = GetUserId();

            if (!await _partService.PartExistsAsync(partId) || await _partService.IsOrdered(partId))
            {
                return BadRequest();
            }

            if (!await _partService.UserIsCreatorAsync(partId, userId))
            {
                return Unauthorized();
            }

            if (!await _materialService.MaterialExistsAsync(model.MaterialId))
            {
                ModelState.AddModelError(nameof(model.MaterialId), "Invalid material!");
            }

            if (!await _materialService.MaterialThicknessExistsAsync(model.MaterialId, model.PartThickness))
            {
                ModelState.AddModelError(nameof(model.PartThickness), "Invalid thickness for given material!");
            }

            if (!ModelState.IsValid)
            {
                model.Materials = await _materialService.GetAllForDropdownAsync();

                return View(model);
            }

            string userEmail = GetUserEmail();

            await _partService.EditAsync(model, partId, userEmail);

            return RedirectToAction(nameof(MyParts));
        }

        [HttpPost]
        public async Task<IActionResult> DownloadScheme(string schemeUrl)
        {
            var fileContent = await _fileManageService.DownloadFile(schemeUrl);

            if (fileContent == null)
            {
                return BadRequest();
            }

            string contentType = "application/octet-stream";
            string fileName = Path.GetFileName(schemeUrl);

            return File(fileContent, contentType, fileName);
        }


        [HttpPost]
        public async Task<IActionResult> Delete(int partId)
        {
            if (!await _partService.PartExistsAsync(partId) || await _partService.IsOrdered(partId))
            {
                return BadRequest();
            }

            string userId = GetUserId();

            if (!await _partService.UserIsCreatorAsync(partId, userId))
            {
                return Unauthorized();
            }

            await _partService.DeleteAsync(partId);

            return RedirectToAction(nameof(MyParts));
        }
    }
}

HelixLaserWorks/Views/Order/Create.cshtml
@model OrderFormModel
@{
    ViewData["Title"] = "Create new order";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

@if (Model.UserParts.Any())
{
    <div class="row">
        <div class="col-sm-12 offset-lg-2 col-lg-8 offset-xl-3 col-xl-6">
            <form method="post">
                <div class="form-group">
                    <label asp-for="Title"></label>
                    <input asp-for="Title" class="form-control" placeholder="Order Title...">
                    <span asp-validation-for="Title" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Description"></label>
                    <input asp-for="Description" rows="4" class="form-control" placeholder="Order description...">
                    <span asp-validation-for="Description" class="small text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="CustomerPhoneNumber"></label>
                    <input asp-for="CustomerPhoneNumber" rows="4" class="form-control" placeholder="Phone Number...">
                    <span asp-validation-for="CustomerPhoneNumber" class="small text-danger"></span>
                </div>

                <label>Select Parts for Order:</label>
                @foreach (var part in Model.UserParts)
                {
                    <div>
                        <input type="checkbox" name="SelectedParts" value="@part.Id" />
                        <label>@part.Name - @part.PartMaterial @part.PartThickness mm</label>
                    </div>
                }
                <span asp-validation-for="SelectedParts" class="small text-danger"></span>

                <div class="text-center">
                    <input class="btn btn-primary mt-3" type="submit" value="Create" )>
                </div>
            </form>
        </div>
    </div>
}
else
{
    <h2 class="text-center">You need to have atleast one part that isn't ordered to create order!</h2>
    <a asp-area="" asp-controller="Part" asp-action="Create" class="btn btn-primary text-c flex-grow-1">Create new part</a>
}

@section Scripts {
    <partial name="_ValidationScriptsPartial" />
}

HelixLaserWorks/Views/Order/CustomersOrders.cshtml
@model OrderPaginatedViewModel
@{
    ViewBag.Title = "Customers Orders";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<form method="get">
    <div class="row">
        
        <div class="form-group col-md-3">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="...">
        </div>

        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="Status"></label>
                <select asp-for="Status" class="form-control">
                    <option value="null">All</option>
                    <option value="0">Pending</option>
                    <option value="1">In Review</option>
                    <option value="2">Ready With Offer</option>
                    <option value="3">Declined By Admin</option>
                    <option value="4">Completed</option>
                </select>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group mt-4 p-2">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalOrdersCount /
        OrderPaginatedViewModel.OrdersPerPage);
}

<ul class="pagination" style="width: 90%">

    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.Orders.Any();
    }

    <li class="page-item col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Order"
           asp-action="CustomersOrders"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-status="@((int?)Model.Status)"><<</a>
    </li>

    @for (int i = 1; i <= maxPage; i++)
    {
        <li class="page-item" style="padding-left: 5px">
            <a class="btn btn-primary @(Model.CurrentPage == @i ? "disabled" : string.Empty)"
               asp-controller="Order"
               asp-action="CustomersOrders"
               asp-route-currentPage="@i"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-status="@((int?)Model.Status)">@i</a>
        </li>
    }

    <li class="page-item col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Order"
           asp-action="CustomersOrders"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-status="@((int?)Model.Status)">>></a>
    </li>

</ul>

@if (!Model.Orders.Any())
{
    <h2 class="text-center">No orders found by the given criteria!</h2>
}

<div class="row">
    @foreach (var order in Model.Orders)
    {
        <div class="card col-md-4">
            <div class="card-body">
                <h5 class="card-title"><span class="fw-bold">Order Title:</span> @order.Title</h5>
                <p class="card-title"><span class="fw-bold">Order Description:</span> @order.Description</p>
                <p class="card-text"><span class="fw-bold">Date of Creation:</span> @order.CreatedOn</p>

                @if (order.Status == "Pending")
                {
                    <p class="card-text btn-warning p-2"><span class="fw-bold">Status:</span> @order.Status</p>
                }
                else if (order.Status == "InReview")
                {
                    <p class="card-text btn-info p-2"><span class="fw-bold">Status:</span> In Review</p>
                }
                else if (order.Status == "DeclinedByAdmin")
                {
                    <p class="card-text btn-danger p-2"><span class="fw-bold">Status:</span> Declined By Admin</p>
                }
                else if (order.Status == "ReadyWithOffer")
                {
                    <p class="card-text btn-primary p-2"><span class="fw-bold">Status:</span> Ready With Offer</p>
                    <a asp-controller="Offer" asp-action="Details" asp-route-offerId="@order.OfferId" class="btn btn-success">View Offer</a>
                }
                else if (order.Status == "Completed")
                {
                    <p class="card-text btn-success p-2"><span class="fw-bold">Status:</span> Completed</p>
                    <a asp-controller="Offer" asp-action="Details" asp-route-offerId="@order.OfferId" class="btn btn-success">View Offer</a>
                }

                <p class="card-text"><span class="fw-bold">Customer Phone Number:</span> @order.CustomerPhoneNumber</p>
                <p class="card-text"><span class="fw-bold">Customer Email:</span> @order.CustomerEmail</p>
                <label class="d-block"><span class="fw-bold">Included Parts:</span></label>
                @foreach (var part in order.Parts)
                {
                    <div class="card" style="margin: 5px">
                        <label class="card-title"><span class="fw-bold">@part.Name</span></label>
                        <p class="card-text">@part.PartMaterial @part.PartThickness mm - @part.Quantity pcs</p>
                        <form asp-controller="Part" asp-action="DownloadScheme" asp-route-schemeUrl="@part.SchemeUrl" method="post">
                            <button class="btn-sm btn-info" type="submit">Download Part Scheme</button>
                        </form>
                    </div>
                }
                <div class="card-footer">
                    @if (order.Status == "Pending")
                    {
                        <form class="d-inline" asp-controller="Order" asp-action="MarkAsReviewed" asp-route-orderId="@order.Id" method="post">
                            <button class="btn-sm btn-warning" type="submit">Mark For Review</button>
                        </form>
                    }

                    @if (order.Status != "ReadyWithOffer" && order.Status != "DeclinedByAdmin" && order.Status != "Completed")
                    {
                        <a style="text-decoration: none" asp-area="" asp-controller="Offer" asp-action="Create" asp-route-orderId="@order.Id" class="btn-sm btn-primary">Send Offer</a>
                        <a style="text-decoration: none" asp-area="" asp-controller="Order" asp-action="Decline" asp-route-orderId="@order.Id" class="btn-sm btn-danger">Decline Order</a>
                    }

                </div>
            </div>
        </div>

    }
</div>

HelixLaserWorks/Views/Order/MyOrders.cshtml
@model OrderPaginatedViewModel
@{
    ViewBag.Title = "My orders";
}

<h2 class="text-center">@ViewBag.Title</h2>
<hr />

<a asp-area="" asp-controller="Order" asp-action="Create" class="btn btn-primary flex-grow-1" style="margin: 5px">Create new order</a>

<form method="get">
    <div class="row">

        <div class="form-group col-md-3">
            <label asp-for="SearchTerm"></label>
            <input asp-for="SearchTerm" class="form-control" placeholder="...">
        </div>

        <div class="form-group col-md-3">
            <div class="form-group">
                <label asp-for="Status"></label>
                <select asp-for="Status" class="form-control">
                    <option value="null">All</option>
                    <option value="0">Pending</option>
                    <option value="1">In Review</option>
                    <option value="2">Ready With Offer</option>
                    <option value="3">Declined By Admin</option>
                    <option value="4">Completed</option>
                </select>
            </div>
        </div>

        <div class="col-md-3">
            <div class="form-group mt-4">
                <input type="submit" value="Search" class="btn btn-primary" />
            </div>
        </div>
    </div>
</form>

@{
    var previousPage = Model.CurrentPage - 1;
    if (previousPage < 1)
    {
        previousPage = 1;
    }

    var maxPage = Math.Ceiling((double)Model.TotalOrdersCount /
        OrderPaginatedViewModel.OrdersPerPage);
}

<ul class="pagination m-2" style="width: 87%">

    @{
        var shouldButtonBeDisabled = Model.CurrentPage == maxPage ||
        !Model.Orders.Any();
    }

    <li class="page-item col-md-6 d-grid gap-2 d-md-flex justify-content-md-start">
        <a class="btn btn-primary @(Model.CurrentPage == 1 ? "disabled" : string.Empty)"
           asp-controller="Order"
           asp-action="MyOrders"
           asp-route-currentPage="@previousPage"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-status="@((int?)Model.Status)"><<</a>
    </li>

    @for (int i = 1; i <= maxPage; i++)
    {
        <li class="page-item" style="padding-left: 5px">
            <a class="btn btn-primary @(Model.CurrentPage == @i ? "disabled" : string.Empty)"
               asp-controller="Order"
               asp-action="MyOrders"
               asp-route-currentPage="@i"
               asp-route-searchTerm="@Model.SearchTerm"
               asp-route-status="@((int?)Model.Status)">@i</a>
        </li>
    }

    <li class="page-item col-md-6 d-grid gap-2 d-md-flex justify-content-md-end">
        <a class="btn btn-primary
           @(shouldButtonBeDisabled ? "disabled" : string.Empty)"
           asp-controller="Order"
           asp-action="MyOrders"
           asp-route-currentPage="@(Model.CurrentPage + 1)"
           asp-route-searchTerm="@Model.SearchTerm"
           asp-route-status="@((int?)Model.Status)">>></a>
    </li>

</ul>

@if (!Model.Orders.Any())
{
    <h2 class="text-center">No orders found !</h2>
}

<div class="row">
    @foreach (var order in Model.Orders)
    {
        <div class="card d-flex justify-content-center align-items-center" style="width: 25rem; margin: 5px">
            <div class="card-body">
                <h5 class="card-title"><span class="fw-bold">Order Title:</span> @order.Title</h5>
                <p class="card-title"><span class="fw-bold">Order Description:</span> @order.Description</p>
                <p class="card-text"><span class="fw-bold">Date of Creation:</span> @order.CreatedOn</p>
                <p class="card-text"><span class="fw-bold">Phone Number:</span> @order.CustomerPhoneNumber</p>
                <label class="d-block"><span class="fw-bold">Included Parts:</span></label>
                @foreach (var part in order.Parts)
                {
                    <div class="card" style="margin: 5px">
                        <label class="card-title"><span class="fw-bold">@part.Name</span></label>
                        <p class="card-text">@part.PartMaterial @part.PartThickness mm - @part.Quantity pcs</p>
                    </div>
                }
            </div>
            @if (order.Status == "Pending")
            {
                <p class="card-text bg-warning" style="padding: 5px; border-radius: 5px"><span class="fw-bold">Status:</span> @order.Status</p>
                <form asp-controller="Order" asp-action="Cancel" asp-route-orderId="@order.Id">
                    <button type="submit" class="btn btn-danger" onclick="return confirm('Are you sure you want to cancel order: @order.Title')">Cancel</button>
                </form>
            }
            else if (order.Status == "InReview")
            {
                <p class="card-text bg-info" style="padding: 5px; border-radius: 5px"><span class="fw-bold">Status:</span> In Review</p>
            }
            else if (order.Status == "DeclinedByAdmin")
            {
                <p class="card-text bg-danger" style="padding: 5px; border-radius: 5px; color:ghostwhite"><span class="fw-bold">Status:</span> @order.Status</p>
                <p class="card-text"><span class="fw-bold">Decline Reason:</span> @order.AdminFeedback</p>
                <form asp-controller="Order" asp-action="Cancel" asp-route-orderId="@order.Id">
                    <button type="submit" class="btn btn-danger">Remove Order</button>
                </form>
            }
            else if (order.Status == "ReadyWithOffer")
            {
                <p class="card-text bg-primary" style="padding: 5px; border-radius: 5px; color:ghostwhite"><span class="fw-bold">Status:</span> Ready With Offer</p>

                <a asp-controller="Offer" asp-action="Details" asp-route-offerId="@order.OfferId" class="btn btn-warning">View Offer</a>

            }
            else if(order.Status == "Completed")
            {
                <p class="card-text bg-success" style="padding: 5px; border-radius: 5px; color:ghostwhite"><span class="fw-bold">Status:</span> @order.Status</p>
                <a asp-controller="Offer" asp-action="Details" asp-route-offerId="@order.OfferId" class="btn btn-warning">View Offer</a>
            }
        </div>

    }
</div>